workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'

stages:
  - build
  - test
  - security
  - deploy

default:
  image: ruby:3.3.0

build_app:
  stage: build
  script:
    - bundle install
    - bundle exec rake build
  rules:
    - if: '$CI_COMMIT_BRANCH'

unit_tests:
  stage: test
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/jacoco.xml
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"'

sast:
  stage: security
  script:
    - semgrep --config auto .
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"'

artifact_scan:
  stage: security
  script:
    - trivy fs --exit-code 1 .
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"'

deploy_test:
  stage: deploy
  environment:
    name: qa
  needs:
    - unit_tests
    - sast
    - artifact_scan
  script:
    - kubectl apply -f k8s/qa.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH'
