include:
  - local: .gitlab/ci/templates/prepare.yml
  - local: .gitlab/ci/security/security.yml

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'

stages:
  - prep
  - test
  - security
  - deploy

default:
  image: ruby:3.3.0

prepare_workspace:
  extends: .prepare_template
  rules:
    - if: '$CI_COMMIT_BRANCH'

deploy_test:
  stage: deploy
  environment:
    name: test
  script:
    - kubectl apply -f k8s/test.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH'
